FROM tailscale/tailscale:latest

COPY .homelab/certs/roots.pem /usr/local/share/ca-certificates/caddy-local-ca.crt
RUN  chmod 644 /usr/local/share/ca-certificates/caddy-local-ca.crt

COPY .homelab/certs/intermediates.pem /usr/local/share/ca-certificates/caddy-local-intermediate-ca.crt
RUN  chmod 644 /usr/local/share/ca-certificates/caddy-local-intermediate-ca.crt

RUN cat /usr/local/share/ca-certificates/caddy-local-ca.crt >> /etc/ssl/certs/ca-certificates.crt
RUN cat /usr/local/share/ca-certificates/caddy-local-intermediate-ca.crt >> /etc/ssl/certs/ca-certificates.crt
RUN update-ca-certificates