# /etc/modules-load.d/wireguard.conf
# WireGuard module
wireguard
# iptables/nftables modules for basic DNAT/SNAT and masquerading
nft_chain_nat
nft_compat
xt_nat
# nftables modules for wg-quick default route
nft_ct
nft_fib_inet
iptable_filter
iptable_nat
ip6table_filter
ip6table_nat