name: Trigger Update & Reload of the Homelab Updater Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    env:
      TEMPLATE_NAME: "debian-vm"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
            authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
            ping: homelab-update-service

      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v4
        with:
          filters: |
            control_plane:
              - 'control-plane/**'
            s_coder:
              - 's-coder/**'
    
      - name: Remove Tailscale DNS
        run: |
          sudo tailscale set --accept-dns=false
        
      - name: Trigger reload of the Control Plane
        if: steps.changes.outputs.control_plane == 'true'
        run: |
          curl -fsS -X GET http://100.114.186.102:2345/update/homelab_control_plane

    #   - name: Trigger reload of the Coder Service
    #     if: steps.changes.outputs.s_coder == 'true'
    #     run: |
    #       curl -fsS -X GET http://100.114.186.102:2345/update/homelab_coder